---
platform: linux 
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest
inputs:
  - name: starterkit
  
outputs:
  - name: resource-app
  
run:
path: mvn
args: ["starterkit/pom.xml", "-DskipTests=true"]
