---
platform: linux 
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest
inputs:
  - name: starterkit
  
outputs:
  - name: starterkit
  
run:
 path: mvn
 args: ["-f", "starterkit/pom.xml", "-DskipTests=true","-DoutputDirectory=starterkit","package"]
