---
platform: linux 
image_resource:
  type: docker-image
  source:
    repository: nitram509/debian-openjdk8-maven-cmake-gcc
    tag: latest
inputs:
  - name: starterkit
  
outputs:
  - name: resource-app
  
run:
path: mvn
args: ["-f", "starterkit/pom.xml", "-DskipTests=true","-DoutputDirectory=resource-app","package"]
